// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "hostDog": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/YAWAL/hostDog/design
// --out=$(GOPATH)\src\github.com\YAWAL\hostDog
// --version=v1.3.1

package app
